; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nano33blesense]
platform = nordicnrf52
board = nano33ble
framework = arduino
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
lib_deps = 
	adafruit/Adafruit PWM Servo Driver Library@^3.0.2
	pololu/VL53L0X@^1.3.1
	arduino-libraries/Arduino_LSM9DS1@^1.1.1
lib_extra_dirs = ${platformio.packages_dir}/framework-arduino-mbed/libraries
build_flags = "-I${platformio.packages_dir}/framework-arduino-mbed/libraries/SPI"
