; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; [env:nano33iot]
; platform = atmelsam
; board = nano_33_iot
; framework = arduino
; upload_protocol = sam-ba
; lib_deps = 
; 	adafruit/Adafruit PWM Servo Driver Library@^3.0.2
; 	arduino-libraries/Arduino_LSM6DS3@^1.0.3
; 	adafruit/Adafruit BusIO@^1.17.4

[env:nano33ble]
platform = nordicnrf52
board = nano33ble
framework = arduino

lib_deps = 
    adafruit/Adafruit PWM Servo Driver Library@^3.0.2
    adafruit/Adafruit BusIO@^1.17.4
    pololu/VL53L0X@^1.3.1
    https://github.com/arduino-libraries/Arduino_BMI270_BMM150.git

build_flags = 
    -std=gnu++17

lib_archive = false
monitor_speed = 115200

lib_ignore = 
    WiFi
    WiFiNINA
    micro_ros_arduino
